SELECT NUM AS ConsecutiveNums  FROM (
SELECT DISTINCT NUM,
LAG(NUM,1) OVER(ORDER BY ID) AS PREV_NUM,
LAG(NUM,2) OVER(ORDER BY ID) AS PREV_PREV_NUM
FROM LOGS) TEMP
WHERE (NUM=PREV_PREV_NUM) AND (NUM=PREV_NUM);